# Site settings
title: Nithin Krishna
email: nithin@codebrahma.com
description: "Just another full stack web developer."
baseurl: ""
url: "http://codebrahma.com/team/#nithin_krishna"
twitter_username: nithinkrishh
github_username:  nithinkrishna

# Build settings
markdown: kramdown
permalink: pretty
